# Generated by Django 4.1.2 on 2022-11-15 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_per',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cat_per', models.IntegerField()),
                ('nomb_cat_per', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('nombre_c', models.CharField(max_length=20)),
                ('apellido_c', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.IntegerField()),
                ('direcc_cli', models.CharField(max_length=50)),
                ('razon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_consult', models.IntegerField()),
                ('nom_consult', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_enfer', models.IntegerField()),
                ('nomb_enfer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_espe', models.IntegerField()),
                ('nomb_espe', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='examen_oral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresionGe', models.CharField(max_length=40)),
                ('cabeza', models.CharField(max_length=40)),
                ('cuello', models.CharField(max_length=40)),
                ('mejillas', models.CharField(max_length=40)),
                ('lengua', models.CharField(max_length=20)),
                ('piso_boca', models.CharField(max_length=20)),
                ('pilares_pala', models.CharField(max_length=40)),
                ('encias', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_pac', models.CharField(max_length=20)),
                ('apellido_pac', models.CharField(max_length=20)),
                ('direcc_pac', models.CharField(max_length=50)),
                ('cel_pac', models.CharField(max_length=9)),
                ('docu_pac', models.CharField(max_length=13)),
                ('fecha_nac_pac', models.DateField()),
                ('sexo_pac', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_per', models.CharField(max_length=20)),
                ('apellido_per', models.CharField(max_length=20)),
                ('cel_per', models.CharField(max_length=9)),
                ('docu_per', models.CharField(max_length=13)),
                ('especialidad', models.CharField(max_length=30)),
                ('cat_per', models.CharField(max_length=30)),
                ('sexo_per', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_trata', models.IntegerField()),
                ('nomb_trata', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
                ('nomb', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=20)),
                ('perfil', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='rec_tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tratami', models.DateField()),
                ('estado', models.CharField(max_length=5)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.personal')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_histo', models.DateField()),
                ('contactar', models.CharField(max_length=40)),
                ('cel_contac', models.CharField(max_length=40)),
                ('alergia', models.CharField(max_length=40)),
                ('toma_medica', models.CharField(max_length=40)),
                ('frecuencia_visi', models.CharField(max_length=40)),
                ('experiencia_trauma', models.CharField(max_length=40)),
                ('extraccion_mue', models.CharField(max_length=40)),
                ('sangre_enci', models.CharField(max_length=40)),
                ('estetica_dental', models.CharField(max_length=40)),
                ('motivo_consul', models.CharField(max_length=40)),
                ('presion_art', models.CharField(max_length=20)),
                ('talla', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=20)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.enfermedad')),
                ('examen_oral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.examen_oral')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.paciente')),
                ('rec_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.rec_tratamiento')),
            ],
        ),
    ]
