# Generated by Django 4.0.5 on 2022-06-03 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_per',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_cat_per', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.IntegerField(max_length=15)),
                ('direcc_cli', models.CharField(max_length=50)),
                ('razon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_consult', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='det_hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_espe', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_pac', models.CharField(max_length=20)),
                ('apellido_pac', models.CharField(max_length=20)),
                ('direcc_pac', models.CharField(max_length=50)),
                ('cel_pac', models.IntegerField(max_length=15)),
                ('docu_pac', models.IntegerField(max_length=12)),
                ('fecha_nac_pac', models.DateField()),
                ('sexo_pac', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_per', models.CharField(max_length=20)),
                ('apellido_per', models.CharField(max_length=20)),
                ('cel_pac', models.IntegerField(max_length=15)),
                ('docu_pac', models.IntegerField(max_length=12)),
                ('cat_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.cat_per')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_trata', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
                ('nomb', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=20)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.personal')),
            ],
        ),
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.det_hist')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='det_hist',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.tratamiento'),
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servMultident.personal')),
            ],
        ),
    ]
