# Generated by Django 4.0.5 on 2022-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servMultident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='nom_consult',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinica',
            name='ruc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='num_consult',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cel_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='docu_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cel_pac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='docu_pac',
            field=models.IntegerField(),
        ),
    ]
