# Generated by Django 4.0.5 on 2022-06-07 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servMultident', '0002_consultorio_nom_consult_alter_clinica_ruc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='cel_pac',
            new_name='cel_per',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='docu_pac',
            new_name='docu_per',
        ),
        migrations.AddField(
            model_name='cat_per',
            name='num_cat_per',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servMultident.consultorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especialidad',
            name='num_espe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='sexo_per',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='num_trata',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo_pac',
            field=models.CharField(max_length=15),
        ),
    ]
