# Generated by Django 4.0.5 on 2022-06-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servMultident', '0004_usuario_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='personal',
        ),
    ]
