# Generated by Django 4.0.5 on 2022-06-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servMultident', '0005_remove_usuario_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cat_per',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personal',
            name='especialidad',
            field=models.CharField(max_length=30),
        ),
    ]
